### ISSUE TITLE
Editar e apagar produtos da lista

### ISSUE THREAD

**Issue by samuelhnrq** [coda-softwares/MeuPDV#1]
Precisam ser implementadas as funções de apagar e editar os produtos da lista. Eu implementei, reutilizando a atividade de cadastro onde eu, passo o objeto pra ser editado por intent, e carregando ele nos campos e depois que o usuário acaba, apaga ou sobrescreve com os novos dados. Só uma possível maneira de implementar.

**Comment by JeffBusterCase** [comment]
Estará no master. Depois de merge no seu.
