### ISSUE TITLE
Editar tela de edição de PDV para gerenciar usuarios

### ISSUE THREAD

**Issue by samuelhnrq** [coda-softwares/MeuPDV#13]
Ela só edita os dados do PDV, é preciso dar a opção de gerenciar os funcionários, além de ter instruções de como inserir novos usuários.

**Comment by samuelhnrq** [comment]
Ainda não está pronto, já lista os participantes, mas ainda não tem a opção de remove-los

**Comment by JeffBusterCase** [comment]
Implementado
